@startuml

start
note
start for "Booking an appointment"
end note

:display list technician based on geo ip;

if (user searches by technician's name?) then ([yes])
    :enter technician's name;
    :list based on a query;
else ([no])
    if (user uses filter?) then ([yes])
    fork
        :fill field address;
    fork again
        :provide a maximum range;
    end fork

    :select type of technician;

    :list based on filter;

    else ([no])


endif
endif

:select technician to book;

repeat

fork
    :add note about issue;
fork again
    if (request home delivery service?) then ([yes])
        fork
            :provide home's address;
        fork again
            :select available date for home's service;
        end fork
    else ([no])
        :select available date;
    endif
end fork

fork

if (pay with card?) then ([yes])
    :fill invoice;
else ([no])
    :cash payment;
endif

fork again

:\t\t\t timer 5m; <<timeEvent>>

end merge

repeat while (session timer expired?) is ([yes]) not ([no])

:systems notify technician;

end

@enduml