package it.dosti.justit.ui.navigation;

public enum Screen {
    LAUNCHER,
    SIDEBAR_SEARCH_LIST,
    MAIN_USER,
    MAIN_TECH,
    PAGE_SHOP,
    BOOKING_PAGE,
    SIDEBAR_LIST_SETTING_USER,
    ACCOUNT_PAGE,
    REVIEWS_BOX,
    ACCOUNT,
    PAYMENTS,
    REGISTER_VIEW,
    REGISTERTEC_VIEW,
    TOPBAR,
    LOGIN,
    REGISTER_SHOP,
    PAGE_SHOP_TECH,
    BOOKINGS,
    SIDEBAR_TECH_LIST,
    BOOKING_PAGE_TECH
}