package it.dosti.justit.ui.navigation;

public enum Screen {
    ACCOUNT_PAGE_USER,
    ACCOUNT_PAGE_TECH,
    ADD_REVIEW,
    BOOKING_PAGE_USER,
    BOOKINGS_LIST_TECH,
    BOOKINGS_LIST_USER,
    LAUNCHER,
    LOGIN,
    MAIN,
    MAIN_TECH,
    MAIN_USER,
    NOTIFICATION_CENTER_TECH,
    NOTIFICATION_CENTER_USER,
    PAGE_SHOP_TECH,
    PAGE_SHOP_USER,
    PAYMENTS,
    REGISTER_SHOP,
    REGISTER_TECH,
    REGISTER_USER,
    REVIEWS_BOX,
    REVIEWS_LIST_TECH,
    SEARCH_LIST_SHOP,
    TAB_PANE_USER_PROFILE,
    TOPBAR

}
