package it.dosti.justit.ui.navigation.cli;

public enum CLIScreen {
    LAUNCHER,
    SIDEBAR_SEARCH_LIST,
    MAIN_USER,
    MAIN_TECH,
    PAGE_SHOP,
    BOOKING_PAGE,
    REVIEWS_BOX,
    REGISTER_VIEW,
    BOOKINGS,
    ADD_REVIEW,
    MESSAGES,
    REGISTERTEC_VIEW,
    ACCOUNT_PAGE,
    PAGE_SHOP_TECH,
    BOOKING_PAGE_TECH,
    REVIEW_TECH,
    MESSAGES_TECH,
    ACCOUNT_TECH,

}
