@startuml

title Book an appointment

actor User
participant LoginGUI <<boundary>>
participant ShopPageGUI <<boundary>>
participant BookingGUI <<boundary>>
participant ShopController <<controller>>
participant BookingController <<controller>>
participant Shop <<entity>>
participant Booking <<entity>>
database DB
actor PaymentServiceProvider


User -> LoginGUI ++: Login

LoginGUI -> ShopPageGUI ++ :  initialize ShopPageGUI
ShopPageGUI -> ShopController ++ :  initialize ShopController

ShopController -->> ShopPageGUI --:
ShopPageGUI -->> LoginGUI --:
deactivate LoginGUI

User -> ShopPageGUI ++: select shop
ShopPageGUI -> ShopController ++: get shop info
ShopController -> Shop ++: <<create>>
deactivate Shop

ShopController ->> DB ++: getShopDB
DB -->> ShopController --
ShopController -->> ShopPageGUI --: show shop details
deactivate ShopPageGUI

User -> BookingGUI ++: select add Booking

BookingGUI -> BookingController ++: add booking

BookingController ->> Booking ++: <<create>>
BookingController ->> Shop ++: get shop data
Booking -->> BookingController --
Shop -->> BookingController --

BookingController -> Booking ++: setup booking
deactivate Booking

BookingController -> DB ++: commit data to DB
deactivate DB

BookingController -> PaymentServiceProvider ++: pay with card
deactivate PaymentServiceProvider

BookingController -->> BookingGUI

deactivate BookingController

BookingGUI -->> User

deactivate BookingGUI

@enduml
