@startuml

title Manage Booking

actor Technician

participant HomePageGUI <<boundary>>
participant BookingPageGUI <<boundary>>
participant BookingController <<controller>>
participant Booking <<entity>>
participant Client <<entity>>
database DB
actor NotificationService

Technician -> HomePageGUI: select ManageBooking
activate HomePageGUI
HomePageGUI -> BookingPageGUI: initialize BookingPageGUI
activate BookingPageGUI

BookingPageGUI -> BookingController ++: <<create>>
BookingController -> Booking ++: <<create>>
deactivate Booking
BookingController ->> DB ++: getAllBookingsDB
DB -->> BookingController --: return Bookings data


BookingController -->> BookingPageGUI --: return bookings data
BookingPageGUI  -->> HomePageGUI -- :
HomePageGUI -->> Technician --:


deactivate BookingPageGUI

Technician -> BookingPageGUI: select show booking info
activate BookingPageGUI

BookingPageGUI -> BookingController ++: get selected booking
BookingController ->> Booking : load booking details
activate Booking
BookingController ->> Client : load user info
activate Client
Booking -->> BookingController --:
Client -->> BookingController --:


BookingController-->> BookingPageGUI --: shows data
BookingPageGUI -->> Technician --:

Technician -> BookingPageGUI: change booking status
activate BookingPageGUI

BookingPageGUI -> BookingController ++: update Booking
BookingController ->> DB ++: save on db
DB -->> BookingController --:
BookingController ->> NotificationService ++: send notification to client
NotificationService  -->> BookingController --:
BookingController -->> BookingPageGUI --:
BookingPageGUI -->> Technician --:

@enduml
