@startuml

title Manage Booking Status

actor Technician

participant HomePageGUI <<boundary>>
participant BookingPageGUI <<boundary>>
participant BookingController <<controller>>
participant Booking <<entity>>
participant Client <<entity>>
database DB
participant Notification <<entity>>
participant NotificationController <<controller>>
actor EmailGateway

Technician -> HomePageGUI: select ManageBooking
activate HomePageGUI
HomePageGUI -> BookingPageGUI: initialize BookingPageGUI
activate BookingPageGUI

BookingPageGUI -> BookingController ++: <<create>>
BookingController -> Booking ++: <<create>>
deactivate Booking
BookingController -> DB ++: getAllBookingsDB
deactivate DB


BookingController -->> BookingPageGUI --: return bookings data
BookingPageGUI  -->> HomePageGUI -- :
HomePageGUI -->> Technician --:


deactivate BookingPageGUI

Technician -> BookingPageGUI: select show booking info
activate BookingPageGUI

BookingPageGUI -> BookingController ++: get selected booking
BookingController -> Client ++: <<create>>
deactivate Client
BookingController ->> Booking : load booking details
activate Booking
BookingController ->> Client : load user info
activate Client
Booking -->> BookingController --:
Client -->> BookingController --:


BookingController-->> BookingPageGUI --: shows data
BookingPageGUI -->> Technician --:

Technician -> BookingPageGUI: change booking status
activate BookingPageGUI

BookingPageGUI -> BookingController ++: update Booking
BookingController -> Booking ++: updateBookingStatus
deactivate Booking
BookingController -> Notification ++: <<create>>
deactivate Notification
BookingController ->> DB ++: save on db
BookingController ->> NotificationController ++: send notification to client
BookingController ->> EmailGateway ++: sendEmailAlert
DB -->> BookingController --:
NotificationController  -->> BookingController --:
EmailGateway -->> BookingController --:
BookingController -->> BookingPageGUI --:
BookingPageGUI -->> Technician --:

@enduml
