@startuml

[*] --> PENDING_PAYMENT

state PENDING_PAYMENT : pay / changeToState(PENDING_CONFIRM)

state PENDING_PAYMENT : reject / changeToState(REJECTED)

state PENDING_CONFIRM : confirm / changeToState(CONFIRMED)

state PENDING_CONFIRM : reject / changeToState(REJECTED)

state CONFIRMED : complete / changeToState(COMPLETED)

state REJECTED

state COMPLETED
PENDING_PAYMENT --> PENDING_CONFIRM : PAY
PENDING_PAYMENT --> PENDING_PAYMENT : CONFIRM / COMPLETE\n InvalidBookingStateException
PENDING_PAYMENT --> REJECTED : REJECT
PENDING_CONFIRM --> CONFIRMED : CONFIRM
PENDING_CONFIRM --> REJECTED : REJECT

CONFIRMED --> COMPLETED : COMPLETE

PENDING_CONFIRM --> PENDING_CONFIRM : COMPLETE\nInvalidBookingStateException

CONFIRMED --> CONFIRMED : CONFIRM / REJECT\nInvalidBookingStateException

REJECTED --> REJECTED : CONFIRM / REJECT / COMPLETE\nInvalidBookingStateException

COMPLETED --> COMPLETED : CONFIRM / REJECT / COMPLETE\nInvalidBookingStateException

@enduml