@startuml
left to right direction
actor "Client" as c
actor "Technician" as t
actor "Notification System" as n
actor "Payment System" as p


package JustIT {
usecase "Add review*" as UC1
usecase "Book an appointment*" as UC2
usecase "View notifications*" as UC3
usecase "Manage shop page*" as UC4
usecase "View booking list*" as UC5
usecase "Export booking" as UC6
usecase "Manage booking status" as UC7
usecase "Process payment" as UC8
usecase "Manage review*" as UC9
}

note bottom of JustIT
"* includes login"
  end note

c --> UC1
c --> UC2
c --> UC3
t --> UC3
t --> UC4
t --> UC5
t --> UC9
UC2 -.> UC8: <<include>>
UC8 --> p
UC2 ---> n
UC7 --> n
UC5 <.d. UC6 : <<extends>>
UC7 .u.> UC5:  <<extends>>

@enduml