@startuml

abstract Subject <<abstract>> {
  +attach(Observer observer)
  +detach(Observer observer)
  #notifyObservers()
}

interface Observer <<interface>> {
  +update(Subject subject)
}

class BookingStatusPublisher <<concrete subject>> {
  - observers: List<Observer>
  - state: Booking
  + attach(Observer observer)
  + detach(Observer observer)
  # notifyObservers()
  + getState(): Booking
  + setState(Booking state)
}

class ReviewCreatedPublisher <<concrete subject>> {
  - observers: List<Observer>
  - state: Review
  + attach(Observer observer)
  + detach(Observer observer)
  + notifyObservers()
  + getState(): Review
  + setState(Review state)
}

class NotificationObserver <<concrete observer>> {
  + update(Subject subject)
}

BookingStatusPublisher .up.|> Subject
ReviewCreatedPublisher .up.|> Subject
NotificationObserver .up.|> Observer
NotificationObserver --> BookingStatusPublisher
NotificationObserver -left-> ReviewCreatedPublisher


Subject o-> Observer : " -observers"

note right of BookingStatusPublisher::notifyObservers
  for (Observer observer : observers) {
      observer.update(this);
  }
end note
@enduml