@startuml

object BookingStatusObserver <<interface observer>>{
+onStatusChanged(Booking change)
}

object ReviewCreatedObserver <<interface observer>>{
+onReviewCreated(Review change)
}

object NotificationObserver <<concrete observer>>{
+onStatusChanged()
+onReviewCreated()
}

object BookingStatusPublisher <<singleton subject>>{
- {static} instance: BookingStatusPublisher
- observers: List<BookingStatusObserver>

+getInstance(): BookingStatusPublisher
+attach()
+notify()
}

object ReviewCreatedPublisher <<singleton subject>> {
- {static} instance: ReviewCreatedPublisher
- observers: List<ReviewCreatedObserver>

+getInstance(): ReviewCreatedPublisher
+attach()
+notify()
}


note left of ReviewCreatedPublisher::notify
  for (ReviewCreatedObserver observer : observers) {
            observer.onReviewCreated(change);
end note

note right of BookingStatusPublisher::notify
  for (BookingStatusObserver observer : observers) {
            observer.onStatusChanged(change);
end note

NotificationObserver --|> BookingStatusObserver
NotificationObserver --|> ReviewCreatedObserver

ReviewCreatedPublisher --> ReviewCreatedObserver
BookingStatusPublisher --> BookingStatusObserver

@enduml
