@startuml
skinparam class {
BackgroundColor<<singleton>> LightYellow

}

class SessionManager <<(S) singleton>> {
    - {static} instance: SessionManager
    - loggedUser: User
    - selectedShop: Shop
    - ownedShop: Shop
    - persistencyType: PersistencyType

    - SessionManager()

    + {static} getInstance(): SessionManager
    + getLoggedUser(): User
    + setLoggedUser(User user): void
    + isClient(): boolean
    + isTechnician(): boolean
    + setCurrentShop(Shop shop): void
    + getCurrentShop(): Shop
    + logout(): void
    + setPersistencyType(PersistencyType persistencyType): void
    + getPersistencyType(): PersistencyType
}
@enduml