@startuml
skinparam class {
BackgroundColor<<singleton>> LightYellow

}

class SessionManager <<(S) singleton>> {
    - {static} instance: SessionManager
    - activeSessions: Map<String, Session>
    - persistencyType: PersistencyType

    - SessionManager()

    + {static} getInstance(): SessionManager
    + createSession(): String
    + setPersistencyType(PersistencyType persistencyType): void
    + getPersistencyType(): PersistencyType
    + logout(String sessionId): void

}
@enduml