@startuml

class Booking <<state machine>> {
    - status: BookingState
    - currentState: BookingStatus
    + goNext(event: BookingEvent)
    + changeToState(state: BookingState)
}

interface BookingStateMachine <<interface state machine>> {
    + goNext(event: BookingEvent)
    + changeToState(state: BookingState)
}

abstract class BookingState <<abstract state>>{
    + confirm(booking: Booking)
    + reject(booking: Booking)
    + complete(booking: Booking)
    + getStatus(): BookingStatus
}

enum BookingEvent <<enumeration>> {
    CONFIRM,
    REJECT,
    COMPLETE
}

enum BookingStatus <<enumeration>> {
    PENDING,
    CONFIRMED,
    REJECTED,
    COMPLETED
}

class PendingState <<concrete state>> {
    +confirm(booking: Booking)
    +reject(booking: Booking)
    +complete(booking: Booking)
    +getStatus(): BookingStatus
}
class ConfirmedState <<concrete state>> {
    +confirm(booking: Booking)
    +reject(booking: Booking)
    +complete(booking: Booking)
    +getStatus(): BookingStatus
}
class RejectedState <<concrete state>> {
    +confirm(booking: Booking)
    +reject(booking: Booking)
    +complete(booking: Booking)
    +getStatus(): BookingStatus
}
class CompletedState <<concrete state>> {
    +confirm(booking: Booking)
    +reject(booking: Booking)
    +complete(booking: Booking)
    +getStatus(): BookingStatus
}

class BookingStateFactory {
    +{static} fromStatus(status: BookingStatus): BookingState
}

Booking -- BookingEvent
Booking -- BookingStatus
Booking --> BookingStateFactory
Booking --> BookingState

BookingState <|-- PendingState
BookingState <|-- ConfirmedState
BookingState <|-- RejectedState
BookingState <|-- CompletedState

BookingStateMachine <|-- Booking

@enduml
